spring:
  application:
    name: hotel-booking
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/hotel-booking
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8070